name: AutoLogin
on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
jobs:
  do-auto-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.5.0'
      # - uses: browser-actions/setup-chrome@latest
      # - uses: cypress-io/github-action@v2
      #   with:
      #     browser: chrome
      #     headless: true
      - run: chrome --version
      - run: npm install
      - run: CHROMIUM_BIN=$(which chrome) npm run start
