# UNIT TEST

name: AutoLogin
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.5.0'
      - run: npm install
      - run: npm run start
