name: AutoLogin
on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
jobs:
  do-auto-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.5.0'
      - name: Chrome headless
        uses: ./
        with:
          browser: chrome
          headless: true
      - run: npm install
      - run: npm run start
